exports.PAYMENT_CASH = "CASH"
exports.PAYMENT_TRANSFER = "TRANSFER"
exports.PAYMENT_PENDING = "PENDING"
exports.PAYMENT_COMPLETED = "COMPLETED"
exports.PAYMENT_FAIL = 'FAIL'

exports.TABLE_BUSY = 'BUSY'
exports.TABLE_AVAILABLE = 'AVAILABLE'